version: '3'
services:
  postgres:
    image: postgres
    ports:
    - 5432:5432
    volumes:
      - ./initial_sql_script.sql:/docker-entrypoint-initdb.d/initial_sql_script.sql
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres